CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'اسپرت',
  price TEXT NOT NULL,
  emoji TEXT DEFAULT '👕',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);